---
include:
  - board: ergohaven
    shield: velvet_v3_ui_left
  - board: ergohaven
    shield: velvet_v3_ui_right
    keymap: velvet_v3_ui_ruen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: velvet_v3_ui_right_ruen-ergohaven-zmk

  - board: ergohaven
    shield: imperial44_left
    keymap: imperial44_ruen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: imperial44_left_ruen-ergohaven-zmk
  - board: ergohaven
    shield: imperial44_right
  - board: ergohaven
    shield: imperial44_qube qube dongle_screen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: imperial44_qube-ergohaven-zmk
  - board: ergohaven
    shield: imperial44_qube qube dongle_screen
    keymap: imperial44_ruen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: imperial44_qube_ruen-ergohaven-zmk
  - board: ergohaven
    shield: imperial44_left_qube

  - board: ergohaven
    shield: trackball
    keymap: trackball_v3.1
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_KEYBOARD_NAME=\"EH\ TB\ v3.1\"
    artifact-name: trackball_v3.1-ergohaven-zmk

  - board: ergohaven
    shield: settings_reset
